### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nuaayuyang** [saic-vul/iterdet#10]
dear author:
when I am running your code ,I have got this error,how can I solve it
KeyError: 'AddHistory is not in the pipeline registry'

**Comment by filaPro** [comment]
Hi @nuaayuyang 
It's strange, because this class is definitely registered here: 
https://github.com/saic-vul/iterdet/blob/master/mmdet/datasets/pipelines/formating.py#L199 .
Have you cloned this repo and not the original `mmdetection`? Can you check if `AddHistory` class is registered in this line in your local code?

**Comment by nuaayuyang** [comment]
dear author:
Thanks for your raplay.
Before that error, I had also got this error, KeyError: 'IterDetFasterRCNN is not in the detector registry'
from your point,what I had done wrong
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"filaPro"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月25日(星期四) 晚上6:01
收件人:&nbsp;"saic-vul/iterdet"<iterdet@noreply.github.com&gt;;
抄送:&nbsp;"余洋"<1184801710@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [saic-vul/iterdet] error (#10)





 
Hi @nuaayuyang
 It's strange, because this class is definitely registered here:
 https://github.com/saic-vul/iterdet/blob/master/mmdet/datasets/pipelines/formating.py#L199 .
 Have you cloned this repo and not the original mmdetection? Can you check if AddHistory class is registered in this line in your local code?

**Comment by filaPro** [comment]
You missed something during installation. Please check https://github.com/saic-vul/iterdet/issues/6 where the same problem was solved.
