### ISSUE TITLE
CrowdHuman evaluation

### ISSUE THREAD

**Issue by Sentient07** [saic-vul/iterdet#11]
Hello,

Thanks for your research and for open-sourcing the code. I am trying to evaluate my method against CrowdHuman benchmark and I could neither find annotation for the test set nor a way of submitting. May I know how did you perform the evaluation on CrowdHuman benchmark? Could you please kindly share the details?

Thank you and regards,

**Comment by filaPro** [comment]
Hi @Sentient07
We evaluated on validation (not test) set, as mentioned in our paper (and probably all other papers sited CrowdHuman).

**Comment by Sentient07** [comment]
Hello,

Thank you for responding. Your answer is much appreciated. We would also probably follow the same as we didn't hear back from their team

Regards,
