### ISSUE TITLE
Evaluation on VOC

### ISSUE THREAD

**Issue by NeetiG26** [saic-vul/iterdet#12]
In the getting started file the command mentioned for evaluation of Pascal VOC dataset includes a file named faster_rcnn_r50_fpn_1x_voc.py but I could not find it in the repo. What should be my next steps to calculate mAP on VOC dataset?

**Comment by filaPro** [comment]
Hi @NeetiG26,
This repo is forked from original [mmdetection](https://github.com/open-mmlab/mmdetection), including all their models and datasets. To calculate mAP on VOC dataset it is better to clone original repo and [train](https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh) or [test](https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_test.sh) with [faster_rcnn_r50_fpn_1x_voc0712](https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py) config.
Here we provide only IdetDet based models on 4 dadasets as mentioned in our [readme.md](https://github.com/saic-vul/iterdet/blob/master/README.md).
