### ISSUE TITLE
The test results are poor

### ISSUE THREAD

**Issue by Sunnyheye** [saic-vul/iterdet#25]
Hello, I processed the crowdhuman dataset according to your script at /tools/convert_dataset/crowd_human.py, and then trained the network with the default configuration file at /configs/iterdet/crowd_human_full_faster_rcnn_r50_fpn_2x.py. The batchsize is 2, split to 2 GPUs. I didn't change the parameters of the Adam optimizer. However, after 24 epochs, my best test result is **_Recall = 92.87, mMR = 85.57, mMR = 52.21_**, which is worse than the result published in your paper (**_Recall = 95.80,  mMR = 88.08, mMR = 49.44_**).

I don't know what the problem is. And can you make some suggestions?
Thank you a lot!

**Comment by filaPro** [comment]
Hi @Sunnyheye,

I think the main reason is that we trained all models with 8 GPUs (as all other models in mmdetection) with 2 images per each. We also provide pretrained models for [v1.2.0](https://github.com/saic-vul/iterdet/releases/tag/v1.2.0) that achieve exactly the same performance as in the paper, and for [v2.0.0](https://github.com/saic-vul/iterdet/releases/tag/v2.0.0) with almost the same scores.

**Comment by Sunnyheye** [comment]
OK, I'll try to train the network with a larger batch size. Thanks a lot!
