### ISSUE TITLE
Is there any configuration file for the faster rcnn that you used as the baseline in the article? I used the resnet50-fpn-faster rcnn in mmdetection to train widerperson and the results were very high, even better than joining iterations. I don’t know why. The result of my running: recall: 97 ap: 90 mmr: 39

### ISSUE THREAD

**Issue by hyz0720** [saic-vul/iterdet#29]

**Comment by filaPro** [comment]
Hi @hyz0720 ,
No, we report baseline results for `CrowdHuman` and `WiderPerson` only from other papers. Looks like in terms of our main metric `AP` your baseline with 90 is a little bit worse, then reported 91.95.

**Comment by hyz0720** [comment]
Then I used two 2080ti graphics cards to process a picture and train 24 epochs of iterdet. The result is "recall": 0.97791, "mAP": 0.91651, "mMR": 0.42071, which is run on a widerperson. The result of mmr is not good, what is the reason for this and what adjustment should I make.

**Comment by filaPro** [comment]
Looks very close to our reported `recall`: 97.15, `AP`: 91.95 and  `mMR`: 40.78. Not sure about adjustments, but we trained with 8 GPUs with 2 images per each.
