### ISSUE TITLE
question about test time

### ISSUE THREAD

**Issue by TTTREE** [saic-vul/iterdet#32]
Thanks for your great work!
What is the FPS running on Crowdhuman?
Have you tested it?

**Comment by filaPro** [comment]
Hi @TTTREE ,
IterDet with 2 iterations is exactly 2 times slower than its baseline detector. You can check FPS for [RetinaNet](https://github.com/open-mmlab/mmdetection/tree/master/configs/retinanet) and [FasterRCNN](https://github.com/open-mmlab/mmdetection/tree/master/configs/faster_rcnn) in original `mmdetection` repo and multiply it by 2.
