### ISSUE TITLE
'CrowdHumanDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by MASON1211** [saic-vul/iterdet#33]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Traceback (most recent call last):
  File "tools/test.py", line 237, in <module>
    main()
  File "tools/test.py", line 176, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/ubuntu/src/mmdetection/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CrowdHumanDataset is not in the dataset registry'

**Reproduction**
1. What command or script did you run?
python tools/test.py configs/iterdet/wider_person_faster_rcnn_r50_fpn_2x.py checkpoints/wider_person_faster_rcnn_r50_fpn_2x.pth --show

A placeholder for the command.
```
I am just trying to run inference. So that maybe I can use it to label my own custom dataset.

**Environment**

pytorch=1.8.1
cuda=11.2
python=3.7

**Comment by filaPro** [comment]
Hi @MASON1211 ,

Can you please check #6? Think, it may help.

**Comment by MASON1211** [comment]
> Hi @MASON1211 ,
> 
> Can you please check #6? Think, it may help.
Hi @filaPro thanks for the reply, 
I followed the install.md replacing with the iterdet repository.

Still I am facing the issue , 

```
(open-mmlab2) ubuntu@ubuntu-akshay:~/src/iterdet$ python tools/test.py configs/iterdet/wider_person_faster_rcnn_r50_fpn_2x.py checkpoints/wider_person_faster_rcnn_r50_fpn_2x.pth --show
Traceback (most recent call last):
  File "tools/test.py", line 237, in <module>
    main()
  File "tools/test.py", line 176, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/ubuntu/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ubuntu/anaconda3/envs/open-mmlab2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CrowdHumanDataset is not in the dataset registry'
```

Does need any config need to be updated that I am missing ?

**Comment by filaPro** [comment]
No, the configs are fine. The thing is, according to your traceback you are calling original `mmdet` registry. However you should call `./mmdet` directory instead. Probably you can update `$PYTHONPATH` or follow the `docker` installation.

**Comment by MASON1211** [comment]
> No, the configs are fine. The thing is, according to your traceback you are calling original `mmdet` registry. However you should call `./mmdet` directory instead. Probably you can update `$PYTHONPATH` or follow the `docker` installation.

Yeah I figured it out , thanks for the insight , my initial build failed due to CUDA_HOME path not set. Which led to all this. 
I tested with some images , the models work great ! 
I will close the issue now, Thanks !
