### ISSUE TITLE
Simpler data handler

### ISSUE THREAD

**Issue by MaloM-CVision** [saic-vul/iterdet#34]
**Describe the feature**
Better way to handle datas. I need to train with my own data and the config setup is really not easy to use. It could be better to put evaluation in a dedicated script, and keep only the parameter needed for the data input.
**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when you use code for the first time with your own data
Ex2. It is inconvenient to search for the right configs and parameter in the multiple config.py files with 300 differents parameters each.

**Related resources**

**Additional context**

**Comment by filaPro** [comment]
Hi @MaloM-CVision ,

This design choice is adapted from [mmdetection](https://github.com/open-mmlab/mmdetection). In my opinion this project structure is great and used by [open-mmlab](https://github.com/open-mmlab) in more then 10 different projects in computer vision handling dozens of models and datasets.

Even in this project, our dataloader is based on default (CustomDataset)[https://github.com/saic-vul/iterdet/blob/master/mmdet/datasets/custom.py#L13] class just with our own evaluation. You can simply inherit from it and use this evaluation with your own data.

**Comment by MaloM-CVision** [comment]
Hi @filaPro , thank you for your quick response.
Maybe I'm not accustomed to this library, i will look further into it !
I need to try harder :)
