### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by NygmaLin** [saic-vul/iterdet#4]
I‘m little confusing about the paper. So I‘d like to know what part of the code has been modified. It can help me have a deeper comprehension about the paper.Thx

**Comment by filaPro** [comment]
The list of all changed files compared to original `mmdetection` is presented in our [README.md](https://github.com/saic-vul/iterdet/blob/master/README.md).
Some highlights:
 * IterDet for FasterRCNN is in `IterDetFasterRCNN` class of [iterdet_faster_rcnn.py](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/iterdet_faster_rcnn.py),
 * IterDet for RetinaNet is in `IterDetRetinaNet` class of [iterdet_retinanet.py](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/iterdet_retinanet.py),
 * History transformation is in `AddHistory` class of [formating.py](https://github.com/saic-vul/iterdet/blob/master/mmdet/datasets/pipelines/formating.py).

**Comment by NygmaLin** [comment]
@filaPro thx ,your reply helps me a lot.
