### ISSUE TITLE
mMR 

### ISSUE THREAD

**Issue by NygmaLin** [saic-vul/iterdet#7]
hello
how do you inference with mMR?  Is there any script which can calculate the mMR?

**Comment by filaPro** [comment]
Hi @NygmaLin 
We used `brambox` library. You can find evaluation function in [mmdet/datasets/crowd_human.py](https://github.com/saic-vul/iterdet/blob/master/mmdet/datasets/crowd_human.py).

**Comment by NygmaLin** [comment]
> Hi @NygmaLin
> We used `brambox` library. You can find evaluation function in [mmdet/datasets/crowd_human.py](https://github.com/saic-vul/iterdet/blob/master/mmdet/datasets/crowd_human.py).

Thanks a lot
