### ISSUE TITLE
IterDet for Instance Segmentation

### ISSUE THREAD

**Issue by sehyungp92** [saic-vul/iterdet#9]
Firstly, many thanks for sharing this interesting work.

I was just wondering how this framework could be used or adapted for instance segmentation, and whether you had explored such considerations.

Kind regards,
Se

**Comment by filaPro** [comment]
Hi @sehyungp92 

We didn't explored instance segmentation in this work, but `mmdetction` supports instance segmentation with its [MaskRCNN](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/mask_rcnn.py) class. Our [IterDetFasterRCNN](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/iterdet_faster_rcnn.py) class if just a few line modification of the [TwoStageDetector](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/two_stage.py). As `MaskRCNN` is also inherited from `TwoStageDetector` it will be easy to modify it to `IterDetMaskRCNN` by just copying everything from `IterDetFasterRCNN` and more careful working with `mask` in `simple_test` method.
